// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tlosromklbciqlhruebz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRsb3Nyb21rbGJjaXFsaHJ1ZWJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNjYzNTIsImV4cCI6MjA2ODg0MjM1Mn0.cBeyN29cZXX-7zAy6l8NQLbCyo_Zz79ebrJ8dS2Mac8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});