// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zpguewuodjfefiwnmosf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpwZ3Vld3VvZGpmZWZpd25tb3NmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0Mzg4ODYsImV4cCI6MjA2OTAxNDg4Nn0.plM485sUjNQ7SoAkpyC-w7esoY42tiDVR21knh3hekw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});